# Generated by Django 4.0.4 on 2022-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_library_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
